block-particles:
  power: true
  particle: END_ROD
holograms:
  - "&6&lСУНДУК УДАЧИ"
  - "&7Нажми, чтобы открыть"
settings:
  no-open-sound: ENTITY_VILLAGER_NO
  animation-sound: BLOCK_NOTE_BLOCK_PLING
messages:
  set-animation: "&7[&6FrameCases&7] &7Анимация успешно &7поставлена"
  no-perms: "&cУ вас недостаточно прав"
  error-argument: "&cОшибка, неверные аргументы!"
  error-instance: "&cОшибка, комманда доступна только живым существам."
  no-contains-case: "&cОшибка, данного кейса не существует"
  error-take-amount: "&cОшибка, у игрока нет столько кейсов"
  case-is-opened: "&cОшибка, кейс уже открывается!"
  error-no-case: "&cОшибка, у вас нет этих кейсов для открытия!"

  click-set-position: "&7[&6FrameDev&7] &7Нажми на блок, чтобы установить позицию для кейсов."
  case-position-put: "&7[&6FrameDev&7] &7Вы успешно установили позицию для кейсов."
  give-key: "&7[&6FrameDev&7] &7Вы успешно выдали кейс &6%case% &7игроку &6%player% &7в количестве &6x%amount%"
  take-key: "&7[&6FrameDev&7] &7Вы успешно забрали кейс &6%case% &7у игрока &6%player% &7в количестве &6x%amount%"
  set-key: "&7[&6FrameDev&7] &7Вы успешно установили &6%amount% &7кейсов, типа - &6%case%, &7игроку &6%player%"
animation-gui-time: 10
gui:
  items:
    ;
    DONATE:
      name: "&6&lКейс с донатом"
      material: TRIPWIRE_HOOK
      lore:
        - ""
        - " &7В этом кейсе вы можете почти любой донат"
        - " &7шансы на кейсы увеличены, есть шанс"
        - " &7выбить любой донат"
        - ""
        - " &7Донаты, которые могут выпасть:"
        - ""
        - " &7SILVER"
        - " &b&lVIP"
        - " &4&lDARK"
        - " &6&l&nFRAME"
        - ""
        - " &7Ключей: &a%keys_donate%"
        - ""
        - " &7Наш сайт: &6framedev.ru"
        - ""
      slot: 21
      amount: 1
      case: donate
      data: 0
    ITEMS:
      name: "&6&lКейс с предметами"
      material: TRIPWIRE_HOOK
      lore:
        - ""
        - " &7В этом кейсе вы можете получить"
        - " &7некоторые предметы, которые могут понадобиться вам в"
        - " &7дальнейшем развитии."
        - ""
        - " &7Ключей: &a%keys_items%"
        - ""
        - " &7Наш сайт: &6framedev.ru"
        - ""
      slot: 23
      amount: 1
      case: items
      data: 0
    ANIMATIONS:
      name: "&6&lВыбор анимации"
      lore:
        - ""
        - " &7В данном разделе вы можете выбрать анимацию для"
        - " &7открытия кейсов, анимация добавляет красоты в"
        - " &7ваше открытие любых кейсов"
        - ""
      material: COOKIE
      amount: 1
      data: 0
      slot: 49
    GLASS_1:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      amount: 1
      data: 0
      slot: 29
    GLASS_2:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      amount: 1
      data: 0
      slot: 30
    GLASS_3:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      amount: 1
      data: 0
      slot: 31
    GLASS_4:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      amount: 1
      data: 0
      slot: 32
    GLASS_5:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      amount: 1
      data: 0
      slot: 33
cases:
  donate:
    silver:
      name: "&7SILVER"
      material: WHITE_SHULKER_BOX
      data: 0
      commands:
        - '[COMMAND] lp user %player% parent add silver'
        - '[TITLE] &aКейс открыт!;&fВаш приз: &7SILVER'
        # - '[ACTIONBAR] '
        # - '[MESSAGE] ' Сообщению игроку который открыл кейс
        # - '[BROADCAST] ' Сообщение всем игрокам в чате
    vip:
      name: "&b&lVIP"
      material: LIGHT_BLUE_SHULKER_BOX
      data: 0
      commands:
        - '[COMMAND] lp user %player% parent add vip'
        - '[TITLE] &aКейс открыт!;&fВаш приз: &b&lVIP'
    dark:
      name: "&4&lDARK"
      material: RED_SHULKER_BOX
      data: 0
      commands:
        - '[COMMAND] lp user %player% parent add dark'
        - '[TITLE] &aКейс открыт!;&fВаш приз: &4&lDARK'
    frame:
      name: "&6&l&nFRAME"
      material: ORANGE_SHULKER_BOX
      data: 0
      commands:
        - '[COMMAND] lp user %player% parent add frame'
        - '[TITLE] &aКейс открыт!;&fВаш приз: &6&l&nFRAME'
    slot: 21
  items:
    diamond:
      name: "&bх32 алмаза"
      material: DIAMOND
      data: 0
      commands:
        - '[COMMAND] give %player% diamond 32'
        - '[TITLE] &aКейс открыт!;&fВаш приз: &bалмазы'
    gold_ingot:
      name: "&eх32 золота"
      material: GOLD_INGOT
      data: 0
      commands:
        - '[COMMAND] give %player% gold_ingot 32'
        - '[TITLE] &aКейс открыт!;&fВаш приз: &eзолото'
    apple:
      name: "&cх16 яблок"
      material: APPLE
      data: 0
      commands:
        - '[COMMAND] give %player% apple 16'
        - '[TITLE] &aКейс открыт!;&fВаш приз: &cяблоки'
    ender_pearl:
      name: "&5х8 перлов"
      material: ENDER_PEARL
      data: 0
      commands:
        - '[COMMAND] give %player% ender_pearl 8'
        - '[TITLE] &aКейс открыт!;&fВаш приз: &5эндер-жемгуг'
    slot: 23
animation-gui:
  items:
    GLASS_1:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 0
    GLASS_2:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 1
    GLASS_3:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 2
    GLASS_4:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 3
    GLASS_5:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 4
    GLASS_6:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 5
    GLASS_7:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 6
    GLASS_8:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 7
    GLASS_9:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 8
    GLASS_10:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 9
    GLASS_11:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 17
    GLASS_12:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 18
    GLASS_13:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 26
    GLASS_14:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 27
    GLASS_15:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 35
    GLASS_16:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 36
    GLASS_17:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 37
    GLASS_18:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 38
    GLASS_19:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 39
    GLASS_20:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 40
    GLASS_21:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 41
    GLASS_22:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 42
    GLASS_23:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 43
    GLASS_24:
      name: "&7"
      material: ORANGE_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 44
    GLASS_25:
      name: "&7"
      material: BLACK_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 13
    GLASS_26:
      name: "&7"
      material: BLACK_STAINED_GLASS_PANE
      data: 0
      amount: 1
      slot: 31
choice:
  items:
    # В этом разделе менять название у кнопок смены анимации и кнопки назад нельзя!
    # Не менять строчку с стрелочкой!
    ANIMATION_1: # <----
      perms: "framecases.animation1"
      no-perms:
        - ""
        - " &7Ошибка, перед тем как использовать эту анимацию"
        - " &7надо где-то ее получить, либо купить"
        - " &7на сайте &6framedev.ru"
        - ""
      name: "&5&lАнимация #1"
      material: ENDER_PEARL
      data: 0
      amount: 1
      slot: 11
    ANIMATION_2: # <----
      perms: "framecases.animation2"
      no-perms:
        - ""
        - " &7Ошибка, перед тем как использовать эту анимацию"
        - " &7надо где-то ее получить, либо купить"
        - " &7на сайте &6framedev.ru"
        - ""
      name: "&8&lАнимация #2"
      material: GUNPOWDER
      data: 0
      amount: 1
      slot: 12
    ANIMATION_3: # <----
      perms: "framecases.animation3"
      no-perms:
        - ""
        - " &7Ошибка, перед тем как использовать эту анимацию"
        - " &7надо где-то ее получить, либо купить"
        - " &7на сайте &6framedev.ru"
        - ""
      name: "&e&lАнимация #3"
      material: YELLOW_DYE
      data: 0
      amount: 1
      slot: 13
    ANIMATION_4: # <----
      perms: "framecases.animation4"
      no-perms:
        - ""
        - " &7Ошибка, перед тем как использовать эту анимацию"
        - " &7надо где-то ее получить, либо купить"
        - " &7на сайте &6framedev.ru"
        - ""
      name: "&c&lАнимация #4"
      material: RED_DYE
      data: 0
      amount: 1
      slot: 14
    ANIMATION_5: # <----
      perms: "framecases.animation5"
      no-perms:
        - ""
        - " &7Ошибка, перед тем как использовать эту анимацию"
        - " &7надо где-то ее получить, либо купить"
        - " &7на сайте &6framedev.ru"
        - ""
      name: "&9&lАнимация #5"
      material: LAPIS_LAZULI
      data: 0
      amount: 1
      slot: 15
    BACK: # <----
      name: "&4&lНазад"
      material: BARRIER
      data: 0
      amount: 1
      slot: 31
players: