name: FrameCases
version: 0.7.3
main: net.framedev.Main
api-version: 1.16
authors:
  - DarkSoulWS
  - FrameDev
commands:
  framecases:
    aliases:
      - cases
depend:
  - ProtocolLib
  - HolographicDisplays